#!/bin/bash
sbatch TestMon1.sh
sbatch TestMon2.sh
sbatch TestMon3.sh
sbatch TestMon4.sh
sbatch TestMon5.sh
sbatch TestMon6.sh
sbatch TestMon7.sh
sbatch TestMon8.sh
sbatch TestMon9.sh
sbatch TestMon10.sh
sbatch TestMon11.sh
sbatch TestMon12.sh
sbatch TestMon13.sh
sbatch TestMon14.sh
sbatch TestMon15.sh
sbatch TestMon16.sh
sbatch TestMon17.sh
sbatch TestMon18.sh
sbatch TestMon19.sh
sbatch TestMon20.sh
sbatch TestMon21.sh
sbatch TestMon22.sh
sbatch TestMon23.sh
sbatch TestMon24.sh
sbatch TestMon25.sh
sbatch TestMon26.sh
sbatch TestMon27.sh
sbatch TestMon28.sh
sbatch TestMon29.sh
sbatch TestMon30.sh
sbatch TestMon31.sh
sbatch TestMon32.sh
sbatch TestMon33.sh
sbatch TestMon34.sh
sbatch TestMon35.sh
sbatch TestMon36.sh
sbatch TestMon37.sh
sbatch TestMon38.sh
sbatch TestMon39.sh
sbatch TestMon40.sh
